version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: eventflow-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: eventflow-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zipkin:
    image: openzipkin/zipkin:3.4
    container_name: eventflow-zipkin
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: eventflow-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.2.0
    container_name: eventflow-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: eventflow-order
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: eventflow-payment
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    container_name: eventflow-inventory
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: eventflow-notification
    ports:
      - "8084:8084"
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  analytics-service:
    build:
      context: .
      dockerfile: analytics-service/Dockerfile
    container_name: eventflow-analytics
    ports:
      - "8086:8086"
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: eventflow-gateway
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - payment-service
      - inventory-service
      - analytics-service
    environment:
      ORDER_SERVICE_HOST: order-service
      ORDER_SERVICE_PORT: 8081
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8082
      INVENTORY_SERVICE_HOST: inventory-service
      INVENTORY_SERVICE_PORT: 8083
      ANALYTICS_SERVICE_HOST: analytics-service
      ANALYTICS_SERVICE_PORT: 8086
